"""create initial tables

Revision ID: 415ca6b8b028
Revises: 15fbf602d829
Create Date: 2025-08-31 18:15:14.755764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415ca6b8b028'
down_revision = '15fbf602d829'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
