"""create_initial_tables

Revision ID: 524702c59901
Revises: 09046def91ca
Create Date: 2025-08-31 18:19:28.546219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524702c59901'
down_revision = '09046def91ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
