"""create initial tables

Revision ID: 5cd5d7e40851
Revises: 9ef778225c93
Create Date: 2025-08-31 18:16:33.774962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd5d7e40851'
down_revision = '9ef778225c93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
